# Dockerfile.node
FROM node:16

# Create a working directory
WORKDIR /app

# Copy the JavaScript file into the container
COPY executions/function.js .

# Run the JavaScript function
CMD ["node", "function.js"]
